version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    ports:
      - 80:80
    volumes:
      - '.:/var/www/html/public'
  php:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    volumes:
      - '.:/var/www/html/public'
